// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czbannuxinkqbcuxkfkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6YmFubnV4aW5rcWJjdXhrZmt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyODc5MjksImV4cCI6MjA2NTg2MzkyOX0.69SSIi1ROSlqPvehruGqIUYaG8ZqMSluAuXsTaSN1DM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);